find_path(GPERFTOOLS_INCLUDE_DIR NAMES gperftools/profiler.h)
find_library(GPERFTOOLS_LIBRARY NAMES libprofiler.so)

set(GPERFTOOLS_FOUND TRUE)

if (NOT GPERFTOOLS_INCLUDE_DIR OR NOT GPERFTOOLS_LIBRARY)
    set(GPERFTOOLS_FOUND FALSE)
endif ()

if (GPERFTOOLS_FOUND)
    set(GPERFTOOLS_LIBRARIES ${GPERFTOOLS_LIBRARY})
    set(GPERFTOOLS_INCLUDE_DIRS ${GPERFTOOLS_INCLUDE_DIR})
endif ()

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Gperftools DEFAULT_MSG GPERFTOOLS_LIBRARIES GPERFTOOLS_INCLUDE_DIRS)

